name: my_flutter_project
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Ensures compatibility with stable Dart versions

dependencies:
  flutter:
    sdk: flutter

  # Sign-in buttons (Google, Facebook, etc.)
  flutter_signin_button: ^2.0.0

  # Local storage
  shared_preferences: ^2.2.2

  # File picker for selecting files (profile pictures, documents, etc.)
  file_picker: ^6.1.1

  # Cupertino Icons (iOS-style icons)
  cupertino_icons: ^1.0.8
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter for Flutter best practices
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/back.jpg
