name: my_flutter_project
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Ensures compatibility with stable Dart versions

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2

  # Email validation package
  email_validator: ^3.0.0  # ✅ Move here under dependencies

  # Sign-in buttons (Google, Facebook, etc.)
  flutter_signin_button: ^2.0.0

  # Local storage
  shared_preferences: ^2.2.2

  # File picker for selecting files (profile pictures, documents, etc.)
  file_picker: ^8.0.7 # Ensure this version works with your platform

  # Cupertino Icons (iOS-style icons)
  cupertino_icons: ^1.0.8

# Firebase (latest as of April 2025)
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.4
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.6

  # Other dependencies
  # image_picker: ^1.0.7
  # http: ^0.13.6
  http: ^0.13.3
  image_picker: ^0.8.4+4  # For picking the video from the gallery
  mime: ^1.0.0  # For detecting file MIME type

  # firebase_core: ^1.10.6
  # firebase_storage: ^10.0.3
  # firebase_auth: ^3.3.4 
  # image_picker: ^1.0.4
  # cloud_firestore: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter for Flutter best practices
  flutter_lints: ^5.0.0

  # Image picker for uploading images/videos
  # image_picker: ^1.0.4  # Make sure to use the latest version

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/free-user-icon-3296-thumb.png
    - assets/images/4c96d16b-b972-4cb3-8523-331cbe0bfd82.png
    - assets/images/e304c83d-ad29-4296-b695-7cefbcd4a3d0.png
    - assets/images/settings icon.png
    - assets/images/back.jpg  # Updated to correct path
    - assets/images/Present2.jpg  # Updated to correct path

# Specify platform-specific dependencies if needed
platforms:
  android: true
  ios: true
  # linux: false
  # macos: false
  # windows: false
